# Generated by Django 4.1 on 2022-08-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=' uma sring', max_length=200),
        ),
    ]
