# Generated by Django 4.1 on 2022-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maapp', '0002_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
